#!/bin/bash

set -uexo pipefail

cd $(dirname $0)/..

tmpdir=$(mktemp -d)

cat > $tmpdir/dockci_ssh_key <<EOF
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACCV9tdU6dz3i59Ci7wK/tkxDYuT4VaQGrdsjK0VWTTUnwAAAIiRdoAVkXaA
FQAAAAtzc2gtZWQyNTUxOQAAACCV9tdU6dz3i59Ci7wK/tkxDYuT4VaQGrdsjK0VWTTUnw
AAAEDFsHlAeii7Aeaivs4Fm26Sk7gr/UGcJCjYy909y19a5pX211Tp3PeLn0KLvAr+2TEN
i5PhVpAat2yMrRVZNNSfAAAABWFAbG1y
-----END OPENSSH PRIVATE KEY-----
EOF

cat > $tmpdir/dock_ci_known_hosts <<EOF
github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
EOF

GIT_SSH_COMMAND="ssh -i $tmpdir/dockci_ssh_key -o StrictHostKeyChecking=yes -o CheckHostIP=no -o \"UserKnownHostsFile=$tmpdir/dock_ci_known_hosts\""

git submodule update --init

rm -r $tmpdir
