#!/bin/bash

# Variables (you can modify these)
CHAIN_ID="cheqd-dev"
NODE_NAME="cheqd-dev"
KEY_NAME="my-key"
MONIKER="local-node"
CHAIN_DIR="$HOME/.testnode"
GENESIS_AMOUNT="100000000000000000000000000000ncheq"  # Very large amount
STAKE_AMOUNT="8246428745600000ncheq"  # Ensure this is >= DefaultPowerReduction
COMMAND="cheqd-noded"

# Install Cosmos SDK if not installed (replace this with your specific chain's SDK)
# Uncomment if you need to install the SDK
# echo "Installing Cosmos SDK..."
# git clone https://github.com/cosmos/cosmos-sdk
# cd cosmos-sdk
# make install
#

# Step 0: Remove the current chain directory (if it exists).
rm -rf $CHAIN_DIR

# Step 1: Initialize the chain
echo "Initializing chain..."
$COMMAND init $NODE_NAME --chain-id $CHAIN_ID --home $CHAIN_DIR --default-denom ncheq

# Step 1.a: Replace the default "stake" with "ncheq" in the genesis file
echo "Replacing default 'stake' with 'ncheq' in genesis file..."
sed -i 's/"stake"/"ncheq"/' $CHAIN_DIR/config/genesis.json

# Step 1.b: Configure feemarket
echo "Configuring feemarket..."
sed -i 's/"fee_denom": "stake"/"fee_denom": "ncheq"/' $CHAIN_DIR/config/genesis.json
sed -i 's/"min_base_gas_price": "1.000000000000000000"/"min_base_gas_price": "0.500000000000000000"/' $CHAIN_DIR/config/genesis.json
sed -i 's/"base_gas_price": "1.000000000000000000"/"base_gas_price": "0.500000000000000000"/' $CHAIN_DIR/config/genesis.json

if [ "$CHEQD_NETWORK" = "mainnet" ]; then
  sed -i 's/"did_namespace": "testnet"/"did_namespace": "mainnet"/' $CHAIN_DIR/config/genesis.json
fi

# Step 2: Generate a keypair (if it doesn't exist already)
if [ -z "$CHEQD_MNEMONIC" ]; then
  echo "Creating key for node..."
  $COMMAND keys add $KEY_NAME --keyring-backend test --home $CHAIN_DIR
else
  echo "Recovering key from mnemonic..."
  printf "%s\n" "$CHEQD_MNEMONIC" | $COMMAND keys add $KEY_NAME --recover --keyring-backend test --home $CHAIN_DIR
fi

# Step 3: Add the generated key as a genesis account
echo "Adding genesis account..."
$COMMAND genesis add-genesis-account $($COMMAND keys show $KEY_NAME -a --keyring-backend test --home $CHAIN_DIR) $GENESIS_AMOUNT --keyring-backend test --home $CHAIN_DIR

# Step 4: Generate a genesis transaction
echo "Generating genesis transaction..."
$COMMAND genesis gentx $KEY_NAME $STAKE_AMOUNT --keyring-backend test --chain-id $CHAIN_ID --home $CHAIN_DIR

# Step 5: Collect genesis transactions into the genesis file
echo "Collecting genesis transactions..."
$COMMAND genesis collect-gentxs --home $CHAIN_DIR

# Step 6: Validate the genesis file
echo "Validating genesis file..."
$COMMAND genesis validate-genesis --home $CHAIN_DIR

# Step 6.a: Cat genesis file
echo "Modified genesis file..."
cat $CHAIN_DIR/config/genesis.json

# Step 7: Copy custom configuration
cp /tmp/cheqd_config.toml $CHAIN_DIR/config/config.toml

# Step 8: Starting the node
echo "Starting cheqd node..."
$COMMAND start --home $CHAIN_DIR --moniker $MONIKER --log_level info
