#!/bin/bash

# Starts a dock test node in docker for testing. Automatically deletes the container on exit.
# Arguments passed to this script are forwarded to the node binary.
#
# Example use:
#
# ```bash
# # Start a local test node
# ./run_node_in_docker --dev
#
# # Start a testnet node
# ./run_node_in_docker --chain=remdev --rpc-external --ws-external --rpc-cors=all
# ```

set -uexo pipefail

source $(dirname $0)/config

# pre-pull
docker pull $CONFIG_DOCK_NODE_IMAGE

# run the node with the random name output by the build command
docker run -p 9944:9944 -p 9933:9933 -p 30333:30333 --rm $CONFIG_DOCK_NODE_IMAGE $@
