#!/bin/bash

# Starts a cheqd test node in docker for testing. Automatically deletes the container on exit.
# Arguments passed to this script are forwarded to the node binary.
#
# Example use:
#
# ```bash
# # Start a local test node
# ./run_cheqd_node_in_docker --dev
#
# # Start a testnet node
# ./run_cheqd_node_in_docker --chain=remdev --rpc-external --ws-external --rpc-cors=all
# ```

set -uexo pipefail
entrypoint="$(realpath $(dirname $0)/cheqd_entrypoint)"
config="$(realpath $(dirname $0)/cheqd_config.toml)"

# pre-pull
docker pull --platform linux/amd64 ghcr.io/cheqd/cheqd-node

# run the node with the random name output by the build command
docker run --platform linux/amd64 -e CHEQD_MNEMONIC="$CHEQD_MNEMONIC" -p 26656:26656 -p 26657:26657 -p 1317:1317 -p 9090:9090 -v $entrypoint:/usr/local/bin/entrypoint.sh -v $config:/tmp/cheqd_config.toml --rm --entrypoint /usr/local/bin/entrypoint.sh ghcr.io/cheqd/cheqd-node start
