#!/bin/bash

set -ueo pipefail

source $(dirname $0)/config

root_dir="$(dirname $0)/.."

# pre-pull
docker pull $CONFIG_DOCK_NODE_IMAGE

container_id=$(
	docker run --rm -d                                        \
        -p 9944:9944 -p 9933:9933 -p 30333:30333            \
        $CONFIG_DOCK_NODE_IMAGE                             \
        --dev --rpc-external --ws-external --rpc-cors=all
)

try_with_node() {
	"$root_dir"/scripts/wait_for_node_rpc_http
	$@
}

if try_with_node $@; then
	exit_code=$?
else
	exit_code=$?
fi

docker kill $container_id

exit $exit_code
