name: Dock blockchain modules tests

on: [pull_request]
jobs:
  master:
    runs-on: ubuntu-latest
    env:
      CONFIG_DOCK_NODE_IMAGE_TAG: "master"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: yarn install --frozen-lockfile
      - run: npm install -g turbo@2.0.5
      - run: turbo telemetry disable
      - run: turbo run test-with-node --filter @docknetwork/dock-blockchain-modules
  mainnet:
    runs-on: ubuntu-latest
    env:
      CONFIG_DOCK_NODE_IMAGE_TAG: "mainnet"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: yarn install --frozen-lockfile
      - run: npm install -g turbo@2.0.5
      - run: turbo telemetry disable
      - run: turbo run test-with-node --filter @docknetwork/dock-blockchain-modules
  testnet:
    runs-on: ubuntu-latest
    env:
      CONFIG_DOCK_NODE_IMAGE_TAG: "testnet"
      DisableTrustRegistryParticipantsTests: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - run: yarn install --frozen-lockfile
      - run: npm install -g turbo@2.0.5
      - run: turbo telemetry disable
      - run: turbo run test-with-node --filter @docknetwork/dock-blockchain-modules
