name: Deploy Documentation
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install and Build 🔧 # Only need to install jsdoc package here and then run docs script
        run: |
          npm install -g turbo
          yarn install --frozen-lockfile --ignore-scripts
          turbo run docs

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Generate mdBook
        run: yarn run mdbook

      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
