name: Integration tests

on: [pull_request]
jobs:
  master:
    runs-on: ubuntu-latest
    env:
      CONFIG_DOCK_NODE_IMAGE_TAG: "master"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test-with-node
  mainnet:
    runs-on: ubuntu-latest
    env:
      CONFIG_DOCK_NODE_IMAGE_TAG: "mainnet"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test-with-node
  testnet:
    runs-on: ubuntu-latest
    env:
      CONFIG_DOCK_NODE_IMAGE_TAG: "testnet"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test-with-node
